### ISSUE TITLE
Error Showing Dialog in FireFox

### ISSUE THREAD

**Issue by HanyAHassan** [niutech/showModalDialog#39] opened 2018-09-05 11:09 UTC
I tried the js file in my project and it didn't work on FireFox browser, then I tried to  run the demo and it showed me the same error in the console "dialog.showModal is not a function"
I'm using the following version of FireFox :
![image](https://user-images.githubusercontent.com/19698635/45089457-40b89d80-b0da-11e8-8f00-3376cd0f43e0.png)
and here's a screenshot of the error : 
![image](https://user-images.githubusercontent.com/19698635/45089567-92f9be80-b0da-11e8-8e00-d56d98f317a6.png)

**Comment by niutech** [comment] 2019-01-07 23:46
This is a duplicate of #29 and #31.

**Closed as completed by niutech** 2019-01-07 23:46 UTC
